### ISSUE TITLE
[feature request] Improve error message when reader auto fails

### ISSUE THREAD

**Issue by malteneuss** [NorfairKing/opt-env-conf#12]
I tried to parse a database url string setting using `reader auto`, which lead to 

```
Failed to read env var: 
DATABASE_URL DATABASE_URL
Database connection string
Un-Read-able value: "postgresql://myuser:mypassword@localhost:5432/mydatabase?sslmode=disable"
```

which i didn't understand (i didn't get the Read hint xD). Would it be possible to add another hint like try parsing as `reader str`?

**Comment by NorfairKing** [comment]
Yes! PR welcome!

**Comment by malteneuss** [comment]
Now that i think about it, shouldn't Read-ing a string into a String value work automatically? If not, would it be possible to make it work, or is this impossible?

**Comment by NorfairKing** [comment]
@malteneuss That's impossible because the `Read` instance of `String` expects `"`quotes`"`.
