### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by NickSeagull** [NorfairKing/opt-env-conf#7]
I see that the library is licensed under LGPL-3.0, and in the @NeoHaskell core library I'm providing a thin layer over it so the users can build their parsers using this library (the core library is essentially adapting this library to use `large-anon` as the configuration API).

Is LGPL-3.0 definitive on this library? Licensing the NeoHaskell core lib under LGPL-3.0 would be an issue because users wouldn't be able to build closed software easily with it and I really wanna support this project and give it credit as one of the enablers of the good DX in the language.

I know that this can be avoided via dynamic linking, but that'd introduce a lot of friction for the users IMO

**Comment by NorfairKing** [comment]
@NickSeagull First of all: there's a static linking exception that says that you are allowed to statically link against opt-env-conf.
All this current license says is that your fork of `opt-env-conf` may not be private if you use it to distribute software.
Your usage of that library is not impacted by this license IIUC.

**Comment by NickSeagull** [comment]
Oh, that's what I get for not reading properly instead of skimming over and seeing LGPL. 

That's definitely great @NorfairKing thank you so much for the prompt response, you rock! ❤️
